# Abstract

We compiled a comprehensive dataset of geo-referenced catches from global tuna fisheries that use fishing gears set at the water's surface. This dataset was created by harmonizing public domain data from the five tuna Regional Fisheries Management Organizations (t-RFMOs) for the period 1958-2021. Under the auspices of the Fisheries and Resources Monitoring System (FIRMS) of the United Nations Food and Agriculture Organization (FAO), we developed a systematic data flow process in collaboration with the t-RFMO Secretariats. This process involved the implementation of a data exchange format adhering to the standards of the FAO Coordinating Working Party on Fishery Statistics (CWP), facilitating the seamless integration of data into the dataset.

Geo-referenced catch data from tuna surface fisheries are reported in either the number of fish or live-weight equivalent (metric tonnes), with some strata providing catches in both units. The catches primarily represent the quantities of retained fish either landed or transhipped at sea and in ports. The data are stratified by year, month, fishing fleet, fishing gear, fishing mode, 1&deg; grid area of longitude and latitude, and taxon.

The dataset encompasses `r length(CA_11_M[species_aggregate == FALSE, unique(species)])` medium- and large-sized pelagic species found in both neritic and oceanic habitats of the world's oceans. This includes `r CA_11_M[species_aggregate == FALSE & species_group_gta %in% c("Temperate tunas", "Tropical tunas", "Neritic tunas"), length(unique(species))]` species of tunas, `r CA_11_M[species_aggregate == FALSE & species_group_gta == "Billfishes", length(unique(species))]` species of billfish, `r CA_11_M[species_aggregate == FALSE & species_group_gta == "Spanish mackerels", length(unique(species))]` species of Spanish mackerels, `r CA_11_M[species_aggregate == FALSE & species_group_gta == "Bonitos and mackerels", length(unique(species))]` species of bonitos, and wahoo. Despite uncertainties and incomplete data due to under-reporting, the dataset also includes reported catches for `r length(CA_11_M[species_group_gta %in% c("Rays", "Sharks") & species_aggregate == FALSE, unique(species)])` species of pelagic sharks and rays that may be either targeted or incidentally caught in tuna and tuna-like fisheries.

The dataset serves as a benchmark for the monitoring and assessment of both artisanal and industrial fisheries using surrounding nets, gillnets, entangling nets, and pole-and-lines from over `r length(unique(CA_11_M$fishing_fleet))` fishing fleets across `r length(unique(CA_11_M$country_code))` countries that have exploited tuna and tuna-like species for subsistence and commercial purposes over more than six decades.

\pagebreak