# Abstract

<!-- _Maximum 170 words recommended_ -->

We constructed the most comprehensive dataset of nominal catches from global tuna fisheries by compiling and harmonizing public domain data from the five tuna Regional Fisheries Management Organizations (t-RFMOs) for the period 1918-2021. Under the auspices of the Fisheries and Resources Monitoring System (FIRMS) of the United Nations Food and Agriculture Organization (FAO),we developed a systematic data flow process in collaboration with the t-RFMO Secretariats. This process involved the implementation of a data exchange format adhering to the standards of the FAO Coordinating Working Party on Fishery Statistics (CWP),facilitating the seamless integration of data into the dataset.

Nominal catch data are expressed in live-weight equivalent (metric tonnes) and primarily represent the quantities of retained fish either landed or transhipped at sea and in ports. In recent years,data from fisheries in the Atlantic and Western-Central Pacific Oceans have partially included amounts of fish discarded dead. The data are stratified by year,fishing fleet,fishing gear,large spatial area,and taxon.

The dataset encompasses `r length(NC[species_aggregate == FALSE, unique(species)])` medium- and large-sized pelagic species found in both neritic and oceanic habitats of the world's oceans. This includes `r length(NC[species_group_gta %in% c("Neritic tunas", "Tropical tunas", "Temperate tunas") & species_aggregate == FALSE, unique(species)])` species of tunas, `r length(NC[species_group_gta == "Billfishes" & species_aggregate == FALSE, unique(species)])` species of billfish, `r length(NC[species_group_gta == "Spanish mackerels" & species_aggregate == FALSE, unique(species)])` species of Spanish mackerels, `r length(NC[species_group_gta == "Bonitos and mackerels" & species_aggregate == FALSE, unique(species)])` species of bonitos,and wahoo. In `r max(NC$year, na.rm = TRUE)`, the global catch for these species was estimated to exceed 5.9 million metric tonnes. Despite uncertainties and incomplete data due to under-reporting, the dataset also includes reported catches for `r length(NC[species_group_gta %in% c("Rays", "Sharks") & species_aggregate == FALSE, unique(species)])` species of pelagic sharks and rays that may be either targeted or incidentally caught in tuna and tuna-like fisheries. The total reported catch of these elasmobranch species was approximately 275,000 metric tonnes in `r max(NC$year, na.rm = TRUE)`

The dataset serves as a benchmark for the monitoring and assessment of both artisanal and industrial fisheries from over `r length(unique(NC$fishing_fleet))` fishing fleets across `r length(unique(NC$fishing_fleet))` fishing fleets from `r length(unique(NC$country_code))` countries that have exploited tuna and tuna-like species for subsistence and commercial purposes over more than seven decades.

\pagebreak