# Background and summary

<!-- _The Background & Summary should provide an overview of the study design and the data generated, including any background information needed to put this study in the context of previous work and the literature, and should reference literature as needed. The section should also briefly outline the broader goals that motivated collection of the data, as well as its potential use. We also encourage authors to include a figure that provides a schematic overview of the study design or workflow_ -->

## Tuna regional fisheries management organizations

Tuna regional fisheries management organizations (tRFMOs) are regional fishery bodies that are responsible for the conservation and management of tuna and tuna-like species, associated species, and their ecosystems throughout the Atlantic, Indian, and Pacific oceans. As most tuna and tuna-like species occur both in areas under national jurisdiction of coastal States and in the high seas, cooperation between countries is key to their sustainable use through international fisheries governance.

While the Inter-American Tropical Tuna Commission (IATTC) covering the eastern Pacific Ocean was established as early as 1949 and the International Commission for the Conservation of Atlantic Tunas (ICCAT) was created in 1966, it is the United Nations Fish Stocks Agreement (UNFSA) adopted in 1995 that established the duty for coastal and foreign fishing States to cooperate in order to ensure conservation and optimum utilization of highly migratory species within and beyond the 200 nm exclusive economic zones (EEZs) [@Balton1996]. Building on already existing international cooperation agreements, the provisions of UNSFA set the basis for the formal establishment of the Commission for the Conservation of Southern Bluefin Tuna (CCSBT) in 1994 [@Goncalves2021], the Indian Ocean Tuna Commission (IOTC) in 1996 [@Kambona1996], and the Western and Central Pacific Fisheries Commission (WCPFC) in 2004 [@Sydnes2001].

<!-- The transnational nature of the tunas and fishing fleets -->

## A global perspective on tuna fisheries

The monitoring and management of tuna and tuna-like species are performed by each RFMO within their area of competence except for CCBST which is responsible for the management of southern bluefin tuna (_Thunnus maccoyii_) whose distribution extends over the Atlantic, Indian, and Western-Central Pacific Ocean. Also, the WCPFC area of competence overlaps with the IOTC area in the eastern Indian Ocean and with the IATTC area in the eastern Pacific Ocean (Fig. XXX). 

The tRFMO Secretariats oversee the collation of different fisheries data sets from tRMFO contracting parties, their curation, and dissemination under specific rules and procedures. Reviewing the status of global tuna fisheries requires combining and harmonizing the various tRFMO data sets. Having a global perspective on tuna fisheries is essential for informing about their temporal trends, contribution to global production, and economic value [@Miyake2004;@Majkowski2007;@Fonteneau2013;@McKinney2020;@Coulter2020]. In addition, tuna markets are globalised and highly integrated across locations and species, making any regional change in catches important for the global industry [@Guillotreau2016]. Finally, tRFMOs are interconnected through fishing capacity as large-scale industrial fleets are highly mobile and can move from one ocean to the other when the management of overcapacity is performed at ocean basin scale [@Aranda2012].

## FAO global capture production database

In parallel to tRFMOs, the UN Food and Agriculture Organisation (FAO) has compiled and published global estimates of annual fishery production statistics from 1950 onwards [@Garibaldi2012]. The global production database includes data for tuna and tuna-like species regrouped under the "Tunas, bonitos, billfishes" species group of the International Standard Statistical Classification for Aquatic Animals and Plants ([ISSCAP](https://www.fao.org/fishery/static/ASFIS/ISSCAAP.pdf)). Data available from tRFMOs are considered of better quality due to the permanent work conducted by the tRFMO in collaboration with their members to improve the data required for stock monitoring and assessments [@Garibaldi2012]. Therefore, they have been used in some cases to replace the FAO statistics, although not in a systematic manner. Furthermore, total annual catches collated from tRFMOs include information on fishing gears as well as some estimates of discards for some years while the FAO global capture production database only reflects the amounts of retained catches [@Garibaldi2012;@Ye2017]. Conversely, data reported to FAO may include catches from the artisanal fisheries sector that might not be reported to tRFMOs in some cases [@JustelRubio2016]. It is also important to note that catch data reported to FAO may be used by tRFMOs such as IOTC to estimate non-reported catches by some countries in some years.

## The Global Tuna Atlas

Time series of total catch available from the five tRFMOs (1) provide a benchmark for assessing the FAO data and identify misreporting issues [@JustelRubio2016], (2) provide better input data than the FAO capture production database for fisheries and stock status assessments based on catch-based models despite the limitations of these approaches [@Zhou2017;@Free2020], and (3) include information on fishing gear which is instrumental for analyses such as catch reconstructions [@Watson2006;@Pauly2016;@Zeller2023].




