# Data Records

_The Data Records section should be used to explain each data record associated with this work, including the repository where this information is stored, and to provide an overview of the data files and their formats. Each external data record should be cited as described below. A data citation should also be placed in the subsection of the Methods containing the data-collection or procedure(s) used to derive the corresponding record._

_Tables can be used to support the data records, specifying the data output resulting from each data-collection or analytical step and the names of the corresponding files should these form part of the archived record._

Nominal catch data are expressed in live-weight equivalent (metric tonnes) and primarily represent the quantities of retained fish either landed or transhipped at sea and in ports. In recent years, data from fisheries in the Atlantic and Western-Central Pacific Oceans have partially included amounts of fish discarded dead. The data are stratified by year, fishing fleet, fishing gear, large spatial area, and taxon.

The dataset encompasses `r length(NC[species_aggregate == FALSE, unique(species)])` medium- and large-sized pelagic species found in both neritic and oceanic habitats of the world's oceans. This includes `r length(NC[species_group_gta %in% c("Neritic tunas", "Tropical tunas", "Temperate tunas") & species_aggregate == FALSE, unique(species)])` species of tunas, `r length(NC[species_group_gta == "Billfishes" & species_aggregate == FALSE, unique(species)])` species of billfish, `r length(NC[species_group_gta == "Spanish mackerels" & species_aggregate == FALSE, unique(species)])` species of Spanish mackerels, `r length(NC[species_group_gta == "Bonitos and mackerels" & species_aggregate == FALSE, unique(species)])` species of bonitos,and wahoo. In `r max(NC$year, na.rm = TRUE)`, the global catch for these species was estimated to exceed 5.9 million metric tonnes. Despite uncertainties and incomplete data due to under-reporting, the dataset also includes reported catches for `r length(NC[species_group_gta %in% c("Rays", "Sharks") & species_aggregate == FALSE, unique(species)])` species of pelagic sharks and rays that may be either targeted or incidentally caught in tuna and tuna-like fisheries. The total reported catch of these elasmobranch species was approximately 275,000 metric tonnes in `r max(NC$year, na.rm = TRUE)`